### ISSUE TITLE
Add address section to "get involved" page

### ISSUE THREAD

**Issue by katoss** [PeerProducedResearch/PeerProducedResearch.github.io#4]
possibly with map and "how to get there"

**Comment by gedankenstuecke** [comment]
I'd say a more general "Contact" page, which has the physical mailing address, email address, maybe a link for where to get to the Slack & also a 'how to get there' section?

**Comment by katoss** [comment]
@gedankenstuecke So a new page instead of including it in "get involved"? Should this page appear in the top menu or just be linked in the footer (now the "contact" link in the footer just opens a window to send you an email) and on the "get involved" page?

I think I'd go for the option: new page + not in top menu but linked in footer and on get-involved page

**Comment by gedankenstuecke** [comment]
Yes, sounds good! 👍

**Comment by katoss** [comment]
67233427bd16227348a9cd849d5b8eb0da0d69b2
